services:
  pg_15:
    image: postgres:15
    environment:
      POSTGRES_DB: easyrent_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5434:5432
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql/data.sql:/docker-entrypoint-initdb.d/2.sql"

  springboot-app:
    image: deploy_demo_v1
    build: .
    ports:
      - 8081:8081
    environment:
      - environment.allowedOrigins=http://localhost:4200,http://localhost:8077,http://localhost:80,http://3.70.177.167
    depends_on:
      - pg_15
